### ISSUE TITLE
Test Annotations

### ISSUE THREAD

**Issue by SamedYalcin** [lojzezust/lars_evaluator#2]
Will test annotations be released?

**Comment by lojzezust** [comment]
We have no intention of releasing the test annotations to the public, to prevent overfitting on the test set. To evaluate and analyse your predictions on the test set, please use the [MaCVi evaluation server](https://macvi.org/).

**Comment by SamedYalcin** [comment]
Is it possible to at least release scene-level attributes for test images?

**Comment by lojzezust** [comment]
Yes, that makes sense. We will release scene-level attributes for the test images soon. I will let you know when the annotations are online (tomorrow if everything goes well). 

Combined with the detailed per-frame results that can be downloaded from the evaluation server, this should provide enough information to conduct interesting analysis of the results.

**Comment by SamedYalcin** [comment]
Thank you for the quick response. I'll be waiting! Feel free to close the issue on your convenience.

**Comment by lojzezust** [comment]
The updated annotations are now available for download on the [LaRS website](https://lojzezust.github.io/lars-dataset/).
